import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { GamesRepository } from '@/lib/repositories/games.repository'
import { useRepository } from '@/lib/repositories/useRepository'

export default function Home() {
  const gamesRepository = new GamesRepository()
  const { useGetAllGames } = useRepository(gamesRepository)
  const { data: allGames } = useGetAllGames()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <pre>{JSON.stringify(allGames, null, 2)}</pre>
        </div>
      </main>
    </>
  )
}
